wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.2
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1683444890.779101
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 23
      4: 3.9.16
      5: 0.15.2
      8:
      - 2
      - 4
      - 5
