name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests
  - pip
  - mlflow
  - hydra-core=1.0.6
  - wandb
  - pip:
      - omegaconf==2.0.6
      - hydra-joblib-launcher==1.1.2
      - protobuf==3.20.1
