name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - pip=20.3.3
  - scikit-learn=1.0.2
  - matplotlib
  - plotly
  - pillow
  - wandb
  - pip:
    - protobuf==3.20.1