name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - pip
  - scikit-learn=0.24.1
  - matplotlib
  - plotly
  - pillow
  - wandb
  - pip:
      - omegaconf==2.0.6
      - protobuf==3.20.1